# Generated by Django 3.1 on 2021-03-16 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_prefix', models.CharField(blank=True, max_length=30, null=True)),
                ('degree_postfix', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_cert_num', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_date', models.DateField()),
                ('post_address', models.CharField(blank=True, max_length=100, null=True)),
                ('zip', models.CharField(blank=True, max_length=6, null=True)),
                ('phone', models.CharField(blank=True, max_length=18, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sportonuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
